default_stages: [pre-commit]
fail_fast: false

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-merge-conflict
      - id: check-ast

  - repo: local
    hooks:
      - id: records-sorter
        name: Sort README
        entry: python .github/helper/record_sorter.py
        language: system
        types: [markdown]
